# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 设置GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --import --batch --passphrase "$GPG_PASSPHRASE"
          echo "$GPG_PUBLIC_KEY" | base64 -d | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      - name: 获取 GPG-key-id
        id: gpg-key-id
        run: |
          GPG_KEY_ID=$(gpg --list-keys --keyid-format long | grep -Eo '([0-9A-F]{16,})')
          echo "::set-output name=gpgKeyId::$GPG_KEY_ID"
      - name: 设置 JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      # 设置 Maven Settings
      - name: 设置 maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          profiles: >
            [
              {
                "id": "ci",
                "properties": {
                  "altSnapshotDeploymentRepository": "${{ secrets.ALT_SNAPSHOT_DEPLOYMENT_REPOSITORY }}",
                  "altReleaseDeploymentRepository": "${{ secrets.ALT_RELEASE_DEPLOYMENT_REPOSITORY }}",
                  "gpg.keyname": "${{ steps.gpg-key-id.outputs.gpgKeyId }}",
                  "gpg.passphrase": "${{ secrets.GPG_PASSPHRASE }}"
                }
              }
            ]
          servers: >
            [
              {
                "id": "ossrh",
                "username": "${{ secrets.MVN_SERVER_USER }}",
                "password": "${{ secrets.MVN_SERVER_PASSWORD }}"
              }
            ]
          repositories: >
            [
              {
                "id": "ossrh-releases",
                "name": "ossrh releases",
                "url": "https://s01.oss.sonatype.org/content/repositories/releases/",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "ossrh-snapshots",
                "name": "ossrh snapshots",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots/",
                "releases": {
                  "enabled": "false"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
      - name: 设置发布版本
        run : |
          command="s/<final.version>.*<\/final.version>/<final.version>$GITHUB_REF_NAME<\/final.version>/g"
          sed -i "${command}" "pom.xml"
          mvn versions:set -DnewVersion=$GITHUB_REF_NAME
      - name: 发布
        run: mvn -B deploy -Pci,ossrh --file pom.xml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
